[package]
name = "fairlauncher.fun"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
solana-program = "1.18.17"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "fairlauncher"
path = "src/main.rs"
